version: '3.5'
services:

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: 'redis:alpine'
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped
