version: '3.5'
services:

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ../data/db:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: 'redis:alpine'
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    command: sh -c "./wait-for ${MYSQL_HOST}:${MYSQL_PORT} -- npx sequelize db:migrate && npm run production"
    ports:
      - 3000:3000
    links:
      - redis
      - database
    volumes:
      - .:/usr/src/app